# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_splits": "00_data.ipynb",
         "TitledStrEx": "00_data.ipynb",
         "PreprocCategorize": "00_data.ipynb",
         "PreprocCategoryBlock": "00_data.ipynb",
         "TextGetter": "00_data.ipynb",
         "KeyGetter": "00_data.ipynb",
         "TransTensorText": "00_data.ipynb",
         "find_first": "00_data.ipynb",
         "split_by_sep": "00_data.ipynb",
         "TokTransform": "00_data.ipynb",
         "TokBatchTransform": "00_data.ipynb",
         "PadBatchTransform": "00_data.ipynb",
         "untuple": "00_data.ipynb",
         "to_tuple": "00_data.ipynb",
         "LMBatchTfm": "00_data.ipynb",
         "Undict": "00_data.ipynb",
         "UndictS2S": "00_data.ipynb",
         "TransformersTextBlock": "00_data.ipynb",
         "TransformersLMBlock": "00_data.ipynb",
         "tokenize": "00_data.ipynb",
         "group_texts": "00_data.ipynb",
         "MultiChoiceTransform": "00_data.ipynb",
         "MultiChoiceBlock": "00_data.ipynb",
         "PadTokBatchTransform": "00_data.ipynb",
         "TokenClassificationBlock": "00_data.ipynb",
         "default_splitter": "01_learner.ipynb",
         "to_device": "01_learner.ipynb",
         "TransCallback": "01_learner.ipynb",
         "GeneratePreds": "01_learner.ipynb",
         "TransLearner": "01_learner.ipynb",
         "MetricCallback": "02_metrics.ipynb",
         "RougeScore": "02_metrics.ipynb",
         "Seqeval": "02_metrics.ipynb"}

modules = ["data.py",
           "learner.py",
           "metrics.py"]

doc_url = "https://aikindergarten.github.io/fasthugs/"

git_url = "https://github.com/aikindergarten/fasthugs/tree/master/"

def custom_doc_links(name): return None
